### ISSUE TITLE
Failed to open whiteList.json

### ISSUE THREAD

**Issue by MmmmHeee** [Mikotwa/FuckLocation#10]
App version: 1.2.2

The app crashes when trying to modify the whitelist and the log reports
`java.io.FileNotFoundException: /data/system/fuck_location_test/whiteList.json: open failed: ENOENT (No such file or directory)`

I navigate to the path `/data/system` but do not find the `fuck_location_test` folder

The full log is attached here
[crashlog.log](https://github.com/Mikotwa/FuckLocation/files/7974147/crashlog.log)

**Comment by MmmmHeee** [comment]
I tried creating an empty whiteList.json at the path and it still crashes. Reinstalling the app not works either. I guess the app failed to initialize some configuration files at first runtime.

**Comment by Mikotwa** [comment]
Must be an issue introduced by recent changes. Will investigate soon.

**Comment by luminislight** [comment]
Same problem here. I found a workaround:
Try installing the previous version that doesn't crash(1.1.0 works for me). And then install the latest version.

**Comment by Mikotwa** [comment]
Should works for v1.2.3.3 now. Would you mind upgrade your module and let me know if this helps? Thanks.

**Comment by MmmmHeee** [comment]
I test the latest app of version 1.2.3.5 and the problem is fixed. Nice work!
