### ISSUE TITLE
Submit a Vietnamese translation

### ISSUE THREAD

**Issue by ThePrimalPea** [Mikotwa/FuckLocation#18]
Cuz idk how to create pull requests or folks so i uploaded the translation in the link below

[values-vi](https://file.io/Act5fyEgzK6w)

**Comment by LeafStative** [comment]
I think you should submit the translation by yourself. That way, your name will appear on the project homepage.

This [video](https://www.youtube.com/watch?v=rgbCcBNZcdQ) might be helpful to you.

**Comment by ThePrimalPea** [comment]
> I think you should submit the translation by yourself. That way, your name will appear on the project homepage.
> 
> This [video](https://www.youtube.com/watch?v=rgbCcBNZcdQ) might be helpful to you.

Nah, i'm not near computer

**Comment by LeafStative** [comment]
> > I think you should submit the translation by yourself. That way, your name will appear on the project homepage.
> > 
> > This [video](https://www.youtube.com/watch?v=rgbCcBNZcdQ) might be helpful to you.
> 
> Nah, i'm not near computer

A web browser is enough

**Comment by Mikotwa** [comment]
> Cuz idk how to create pull requests or folks so i uploaded the translation in the link below
> 
> [values-vi](https://file.io/Act5fyEgzK6w)

Thank you for your translation! 🎉 Will be added in the next (few) update(s).

**Comment by Mikotwa** [comment]
> values-vi

Seems your link have been deleted by provider. Would you like to directly upload the file here and I will migrate to the branch? Thanks

**Comment by ThePrimalPea** [comment]
> Seems your link has been deleted by the provider. Would you like to directly upload the file here and I will migrate to the branch? Thanks

Oops, here is the new link
https://a.tmp.ninja/KZnYWjtS.xml

**Comment by Mikotwa** [comment]
> Oops, here is the new link
> https://a.tmp.ninja/KZnYWjtS.xml

Thank you! It will be included in a public release in the next update.

**Comment by Mikotwa** [comment]
Included in v1.2.6.1 :rocket:
