### ISSUE TITLE
安卓11，企业微信设置以后无法获取位置信息

### ISSUE THREAD

**Issue by xiaohuid** [Mikotwa/FuckLocation#26]
安卓11，企业微信设置以后无法获取位置信息

----
[ 2022-02-21T17:00:03.708     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:03.709     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:03.709     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:03.719     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:03.719     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:03.719     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:04.004     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.005     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return empty AllCellInfo for testing purpose.
[ 2022-02-21T17:00:04.006     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.006     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return empty AllCellInfo for testing purpose.
[ 2022-02-21T17:00:04.009     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: in registerGnssStatusCallback (R)! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.009     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: in whiteList! Dropping register request...
[ 2022-02-21T17:00:04.010     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.010     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return custom cell data information
[ 2022-02-21T17:00:04.010     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Using LTE Network...
[ 2022-02-21T17:00:04.016     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Returning custom result: CellIdentityLte:{ mCi=99765811 mPci=178 mTac=24322 mEarfcn=1850 mBands=[3] mBandwidth=20 mMcc=460 mMnc=11 mAlphaLong=CHN-CT mAlphaShort=CT mAdditionalPlmns={} mCsgInfo=null}
[ 2022-02-21T17:00:04.019     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.020     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return custom cell data information
[ 2022-02-21T17:00:04.020     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Using LTE Network...
[ 2022-02-21T17:00:04.024     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Returning custom result: CellIdentityLte:{ mCi=99765811 mPci=178 mTac=24322 mEarfcn=1850 mBands=[3] mBandwidth=20 mMcc=460 mMnc=11 mAlphaLong=CHN-CT mAlphaShort=CT mAdditionalPlmns={} mCsgInfo=null}
[ 2022-02-21T17:00:04.068     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.069     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return empty AllCellInfo for testing purpose.
[ 2022-02-21T17:00:04.069     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.070     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return empty AllCellInfo for testing purpose.
[ 2022-02-21T17:00:04.072     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: in registerGnssStatusCallback (R)! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.073     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: in whiteList! Dropping register request...
[ 2022-02-21T17:00:04.075     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.076     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return custom cell data information
[ 2022-02-21T17:00:04.076     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] Using LTE Network...
[ 2022-02-21T17:00:04.085     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] Returning custom result: CellIdentityLte:{ mCi=99765811 mPci=178 mTac=24322 mEarfcn=1850 mBands=[3] mBandwidth=20 mMcc=460 mMnc=11 mAlphaLong=CHN-CT mAlphaShort=CT mAdditionalPlmns={} mCsgInfo=null}
[ 2022-02-21T17:00:04.087     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.tencent.wework
[ 2022-02-21T17:00:04.088     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in whiteList! Return custom cell data information
[ 2022-02-21T17:00:04.088     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Using LTE Network...
[ 2022-02-21T17:00:04.095     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] Returning custom result: CellIdentityLte:{ mCi=99765811 mPci=178 mTac=24322 mEarfcn=1850 mBands=[3] mBandwidth=20 mMcc=460 mMnc=11 mAlphaLong=CHN-CT mAlphaShort=CT mAdditionalPlmns={} mCsgInfo=null}
[ 2022-02-21T17:00:04.121     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:04.121     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:04.121     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:04.126     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.tencent.wework
[ 2022-02-21T17:00:04.126     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:04.126     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: BSSID: , SSID: AndroidAP
[ 2022-02-21T17:00:04.132     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:04.132     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:04.132     1000:  1573:  5987 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:04.303    10307:  6214:  7923 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:00:05.708     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:05.709     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:05.709     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.tencent.wework
[ 2022-02-21T17:00:05.710     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:05.710     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: BSSID: , SSID: AndroidAP
[ 2022-02-21T17:00:06.151     1000:  1573:  1762 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:06.160     1000:  1573:  1762 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:06.160     1000:  1573:  1762 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:06.163     1000:  1573:  1762 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:06.991     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:07.378     1000:  1573:  3217 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:07.383     1000:  1573:  4894 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:08.233     1001:  3482:  3712 I/LSPosed-Bridge  ] FL: [Cellar] in getNeighboringCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.276     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: [Cellar] in notifyCellInfoForSubscriber!
[ 2022-02-21T17:00:08.324     1001:  3482:  3545 I/LSPosed-Bridge  ] FL: [Cellar] in getNeighboringCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.327     1001:  3482:  4287 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.331     1001:  3482:  4287 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.333     1001:  3482:  4287 I/LSPosed-Bridge  ] FL: [Cellar] in getNeighboringCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.335     1001:  3482:  4287 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.341     1001:  3482:  4287 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:08.608     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: in registerGnssStatusCallback (R)! Caller package name: com.google.android.gms
[ 2022-02-21T17:00:09.200     1000:  1573:  3951 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:09.267     1000:  1573:  3710 I/LSPosed-Bridge  ] FL: in getLastLocation! Caller package name: com.google.android.gms
[ 2022-02-21T17:00:09.270     1000:  1573:  4897 I/LSPosed-Bridge  ] FL: in getLastLocation! Caller package name: com.google.android.gms
[ 2022-02-21T17:00:09.273     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: in getLastLocation! Caller package name: com.google.android.gms
[ 2022-02-21T17:00:09.415     1000:  1573:  3109 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:09.697     1000:  1573:  3397 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:09.704     1000:  1573:  5964 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:00:09.807     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:09.938     1000:  1573:  5964 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:10.330     1000:  1573:  3951 I/LSPosed-Bridge  ] FL: in registerGnssStatusCallback (R)! Caller package name: com.google.android.gms
[ 2022-02-21T17:00:10.383     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:10.580     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:10.647     1000:  1573:  4322 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.google.android.gms
[ 2022-02-21T17:00:12.154     1000:  1573:  4322 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:12.155     1000:  1573:  4322 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:12.156     1000:  1573:  4322 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:13.776     1000:  1573:  4897 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.tencent.wework
[ 2022-02-21T17:00:13.776     1000:  1573:  3110 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:13.776     1000:  1573:  3710 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:13.777     1000:  1573:  4897 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:13.777     1000:  1573:  4897 I/LSPosed-Bridge  ] FL: BSSID: , SSID: AndroidAP
[ 2022-02-21T17:00:13.879     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getNeighboringCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:00:14.363     1000:  1573:  3110 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.tencent.wework
[ 2022-02-21T17:00:14.365     1000:  1573:  3110 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:14.365     1000:  1573:  3110 I/LSPosed-Bridge  ] FL: BSSID: , SSID: "Android-AP"
[ 2022-02-21T17:00:14.392     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.tencent.wework
[ 2022-02-21T17:00:14.393     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: in whitelist! Return custom WiFi information
[ 2022-02-21T17:00:14.393     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: BSSID: , SSID: AndroidAP
[ 2022-02-21T17:00:26.304     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:26.319     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:26.319     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:26.322     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:31.665     1000:  1573:  2489 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: android
[ 2022-02-21T17:00:32.816    10307:  6214:  9663 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:00:47.985     1000:  1573:  4811 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:47.985     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:00:48.120     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:48.135     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:48.135     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:00:48.142     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:00:51.985     1000:  1573:  2574 I/LSPosed-Bridge  ] FL: [Cellar] in notifyCellInfoForSubscriber!
[ 2022-02-21T17:00:53.610     1000:  1573:  2489 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: android
[ 2022-02-21T17:01:01.971    10102: 10969: 10969 I/LSPosed         ] Loading modules for com.google.android.documentsui/10102
[ 2022-02-21T17:01:01.972    10102: 10969: 10969 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:01.979    10102: 10969: 10969 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:02.145    10082: 10104: 10104 I/LSPosed         ] Loading modules for com.android.externalstorage/10082
[ 2022-02-21T17:01:02.147    10082: 10104: 10104 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:02.153    10082: 10104: 10104 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:02.271    10080: 10131: 10131 I/LSPosed         ] Loading modules for android.process.media/10080
[ 2022-02-21T17:01:02.272    10080: 10131: 10131 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:02.278    10080: 10131: 10131 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:02.442    10108: 10155: 10155 I/LSPosed         ] Loading modules for com.android.traceur/10108
[ 2022-02-21T17:01:02.443    10108: 10155: 10155 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:02.449    10108: 10155: 10155 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:02.899    10240: 10264: 10264 I/LSPosed         ] Loading modules for com.google.android.apps.docs/10240
[ 2022-02-21T17:01:02.900    10240: 10264: 10264 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:02.908    10240: 10264: 10264 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:03.159     1000:  1573:  4344 I/LSPosed-Bridge  ] FL: [Cellar] in notifyCellInfoForSubscriber!
[ 2022-02-21T17:01:04.427     1000:  1573:  3396 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:01:04.603     1000:  1573:  5893 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:01:04.612     1000:  1573:  3110 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:01:05.430    10307:  6214: 10491 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:01:05.488    10307:  6214: 10496 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:01:06.491    10307:  6214: 10516 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:01:07.496    10307:  6214: 10521 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:01:08.503    10307:  6214: 10529 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.support.v7.app.ﹳיٴ$1.afterHookedMethod(Unknown Source:9)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getString(Unknown Source:11)
	at o.fnk.c(SourceFile:250)
	at o.qy.b(SourceFile:161)
	at com.huawei.bone.ui.setting.NotificationPushListener.a(SourceFile:738)
	at com.huawei.bone.ui.setting.NotificationPushListener.d(SourceFile:72)
	at com.huawei.bone.ui.setting.NotificationPushListener$5.run(SourceFile:660)
	at com.huawei.haf.threadpool.ThreadPoolManager$e.run(SourceFile:369)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[ 2022-02-21T17:01:09.769     1000:  1573:  5893 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:01:09.770     1000:  1573:  4897 I/LSPosed-Bridge  ] FL: In getScanResults with caller: com.amap.android.location
[ 2022-02-21T17:01:09.810     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.amap.android.location
[ 2022-02-21T17:01:09.813     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getCellLocation! Caller package name: com.amap.android.location
[ 2022-02-21T17:01:09.815     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getNeighboringCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:01:09.822     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:01:09.824     1001:  3482:  4196 I/LSPosed-Bridge  ] FL: [Cellar] in getAllCellInfo! Caller package name: com.amap.android.location
[ 2022-02-21T17:01:09.946     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:01:09.948     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:01:09.948     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: in handleLocationChangedLocked (R)! Removing whitelisted apps...
[ 2022-02-21T17:01:09.951     1000:  1573:  3593 I/LSPosed-Bridge  ] FL: Finished delivering altered records...
[ 2022-02-21T17:01:14.373    10240: 10687: 10687 I/LSPosed         ] Loading modules for com.google.android.apps.docs/10240
[ 2022-02-21T17:01:14.374    10240: 10687: 10687 I/LSPosed-Bridge  ] Loading module com.flo354.xposed.applocale from /data/app/~~ocmfUJe65j2ZcMVkS3LWFQ==/com.flo354.xposed.applocale-MsaYHkaOUKAgDBdlgUDwDg==/base.apk
[ 2022-02-21T17:01:14.383    10240: 10687: 10687 I/LSPosed-Bridge  ]   Loading class com.flo354.xposed.applocale.XposedMod
[ 2022-02-21T17:01:15.910     1000:  1573:  3217 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:01:16.043     1000:  1573:  3327 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket
[ 2022-02-21T17:01:16.046     1000:  1573:  3397 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.huawei.appmarket

**Comment by tpnet** [comment]
@Mikotwa  大佬，
我这边也是，1.2.13 还是这样，提示信号弱无法定位
[企业微信信号弱.txt](https://github.com/Mikotwa/FuckLocation/files/8469030/default.txt)
。

**Comment by Mikotwa** [comment]
> @Mikotwa 大佬， 我这边也是，1.2.13 还是这样，提示信号弱无法定位。 Flyme9.2.0.2A，Android11，企业微信4.0.3。 [企业微信信号弱.txt](https://github.com/Mikotwa/FuckLocation/files/8469030/default.txt) 。

1. 请尝试完善基站信息
2. 请不要在已关闭的 issue 下方回复。如有疑问，请另开 issue
