### ISSUE TITLE
点设置闪退

### ISSUE THREAD

**Issue by lbbbal** [Mikotwa/FuckLocation#3]
机型：小米10u
安卓版本：11
框架：lsp
1.03更新到1.06之后点设置闪退

**Comment by lbbbal** [comment]
> 机型：小米10u 安卓版本：11 框架：LSP 1.03版本没问题，更新1.06之后点设置直接闪退 (不知道如何发log) ![Screenshot_2022-01-13-14-37-36-085_bin mt plus](https://user-images.githubusercontent.com/97658208/149278546-5a5ef152-22e3-474c-8221-79dac9cfe849.jpg) ![Screenshot_2022-01-13-14-38-07-920_bin mt plus](https://user-images.githubusercontent.com/97658208/149278564-a6522fb2-73fb-44cb-ac14-830332053c39.jpg)

**Comment by Mikotwa** [comment]
No log no fix.
