### ISSUE TITLE
更新1.2.11版本后虚拟定位功能失效

### ISSUE THREAD

**Issue by zzc10086** [Mikotwa/FuckLocation#33]
测试环境：小米6 LinageOS18.1 Android11
LSPosed 1.8.0(6482)-Riru：已勾选FuckLocation作用域默认系统框架和电话服务并重启。

FuckLocation已设置经纬度，其余留空。
白名单勾选了 高德地图,定位显示的依旧是实际位置

回退1.2.8.2后功能正常
[LSPosed_2022-03-25T04_19_31.458.zip](https://github.com/Mikotwa/FuckLocation/files/8385623/LSPosed_2022-03-25T04_19_31.458.zip)

**Comment by Mikotwa** [comment]
看起来模块没有正确处理：
1. 是小米机器
2. 但刷了非 MIUI 类型系统
的情况。

请耐心等待后续修复

**Comment by Mikotwa** [comment]
请尝试最新的 CI 版本，该版本尝试修复了这一问题。如果依然有问题，欢迎反馈

**Comment by Mikotwa** [comment]
经反馈，该问题已解决。将关闭此 issue。如仍有问题，欢迎新开 issue 反馈。
